CREATE TABLE IF NOT EXISTS platform_global_costs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    module VARCHAR(32) NOT NULL,
    route_key VARCHAR(64) NULL,
    country_code VARCHAR(8) NULL,
    prefix_code VARCHAR(32) NULL,
    provider VARCHAR(64) NULL,
    carrier VARCHAR(128) NULL,
    cost_price DECIMAL(14,6) NOT NULL DEFAULT 0,
    currency VARCHAR(8) NOT NULL DEFAULT 'BRL',
    active TINYINT(1) NOT NULL DEFAULT 1,
    effective_date DATETIME NOT NULL,
    notes TEXT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_platform_global_cost_module (module, active),
    KEY idx_platform_global_cost_scope (module, route_key, country_code, provider),
    KEY idx_platform_global_cost_effective (effective_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS platform_global_cost_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    platform_global_cost_id BIGINT UNSIGNED NULL,
    module VARCHAR(32) NOT NULL,
    route_key VARCHAR(64) NULL,
    country_code VARCHAR(8) NULL,
    provider VARCHAR(64) NULL,
    old_cost_price DECIMAL(14,6) NULL,
    new_cost_price DECIMAL(14,6) NULL,
    old_currency VARCHAR(8) NULL,
    new_currency VARCHAR(8) NULL,
    old_active TINYINT(1) NULL,
    new_active TINYINT(1) NULL,
    impact_summary VARCHAR(255) NULL,
    notes TEXT NULL,
    payload_json LONGTEXT NULL,
    executed_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_platform_global_cost_logs_ref (platform_global_cost_id, created_at),
    KEY idx_platform_global_cost_logs_module (module, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
