CREATE TABLE IF NOT EXISTS marketing_campaigns (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenancy_id VARCHAR(64) NOT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    name VARCHAR(160) NOT NULL,
    description TEXT NULL,
    objective VARCHAR(60) NOT NULL,
    campaign_type VARCHAR(60) NOT NULL DEFAULT 'video',
    primary_text TEXT NULL,
    ad_title VARCHAR(160) NULL,
    call_to_action VARCHAR(80) NULL,
    destination_link VARCHAR(500) NULL,
    whatsapp_number VARCHAR(30) NULL,
    city VARCHAR(120) NULL,
    state VARCHAR(80) NULL,
    age_start SMALLINT UNSIGNED NULL,
    age_end SMALLINT UNSIGNED NULL,
    interests TEXT NULL,
    budget_daily DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    budget_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    start_date DATE NULL,
    end_date DATE NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    thumbnail_path VARCHAR(500) NULL,
    video_path VARCHAR(500) NULL,
    account_id VARCHAR(120) NULL,
    meta_campaign_id VARCHAR(120) NULL,
    meta_adset_id VARCHAR(120) NULL,
    meta_ad_id VARCHAR(120) NULL,
    meta_creative_id VARCHAR(120) NULL,
    sync_status VARCHAR(30) NOT NULL DEFAULT 'pending',
    sync_response_raw LONGTEXT NULL,
    deleted_at DATETIME NULL,
    archived_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_marketing_campaigns_tenancy (tenancy_id),
    KEY idx_marketing_campaigns_status (status),
    KEY idx_marketing_campaigns_sync_status (sync_status),
    KEY idx_marketing_campaigns_dates (start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_campaign_assets (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    campaign_id INT UNSIGNED NOT NULL,
    tenancy_id VARCHAR(64) NOT NULL,
    asset_type VARCHAR(30) NOT NULL,
    original_name VARCHAR(255) NULL,
    storage_path VARCHAR(500) NOT NULL,
    public_path VARCHAR(500) NOT NULL,
    mime_type VARCHAR(120) NULL,
    extension VARCHAR(16) NULL,
    size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    duration_seconds DECIMAL(10,2) NULL,
    width INT UNSIGNED NULL,
    height INT UNSIGNED NULL,
    generated_thumbnail_path VARCHAR(500) NULL,
    metadata_json LONGTEXT NULL,
    uploaded_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_marketing_assets_campaign (campaign_id),
    KEY idx_marketing_assets_tenancy (tenancy_id),
    KEY idx_marketing_assets_type (asset_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_campaign_budgets (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    campaign_id INT UNSIGNED NOT NULL,
    tenancy_id VARCHAR(64) NOT NULL,
    budget_daily DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    budget_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    currency_code CHAR(3) NOT NULL DEFAULT 'BRL',
    budget_status VARCHAR(30) NOT NULL DEFAULT 'planned',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_marketing_budget_campaign (campaign_id),
    KEY idx_marketing_budget_tenancy (tenancy_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_campaign_audiences (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    campaign_id INT UNSIGNED NOT NULL,
    tenancy_id VARCHAR(64) NOT NULL,
    audience_name VARCHAR(160) NULL,
    city VARCHAR(120) NULL,
    state VARCHAR(80) NULL,
    age_start SMALLINT UNSIGNED NULL,
    age_end SMALLINT UNSIGNED NULL,
    interests_json LONGTEXT NULL,
    details_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_marketing_audience_campaign (campaign_id),
    KEY idx_marketing_audience_tenancy (tenancy_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_campaign_metrics (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    campaign_id INT UNSIGNED NOT NULL,
    tenancy_id VARCHAR(64) NOT NULL,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_per_click DECIMAL(12,4) NOT NULL DEFAULT 0.0000,
    leads BIGINT UNSIGNED NOT NULL DEFAULT 0,
    conversations_started BIGINT UNSIGNED NOT NULL DEFAULT 0,
    investment_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    conversions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    estimated_return DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    sync_source VARCHAR(40) NOT NULL DEFAULT 'manual',
    snapshot_date DATE NULL,
    last_synced_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_marketing_metrics_campaign (campaign_id),
    KEY idx_marketing_metrics_tenancy (tenancy_id),
    KEY idx_marketing_metrics_snapshot (snapshot_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_campaign_history (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    campaign_id INT UNSIGNED NULL,
    tenancy_id VARCHAR(64) NOT NULL,
    user_id INT UNSIGNED NULL,
    action VARCHAR(60) NOT NULL,
    action_label VARCHAR(160) NULL,
    details_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_marketing_history_campaign (campaign_id),
    KEY idx_marketing_history_tenancy (tenancy_id),
    KEY idx_marketing_history_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_meta_settings (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenancy_id VARCHAR(64) NOT NULL,
    meta_access_token LONGTEXT NULL,
    meta_ad_account_id VARCHAR(120) NULL,
    meta_pixel_id VARCHAR(120) NULL,
    meta_page_id VARCHAR(120) NULL,
    whatsapp_destination VARCHAR(30) NULL,
    meta_business_id VARCHAR(120) NULL,
    connection_status VARCHAR(30) NOT NULL DEFAULT 'not_configured',
    last_connection_check_at DATETIME NULL,
    last_error TEXT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_marketing_meta_settings_tenancy (tenancy_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_meta_sync_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    campaign_id INT UNSIGNED NULL,
    tenancy_id VARCHAR(64) NOT NULL,
    user_id INT UNSIGNED NULL,
    action VARCHAR(60) NOT NULL,
    request_payload LONGTEXT NULL,
    response_payload LONGTEXT NULL,
    success TINYINT(1) NOT NULL DEFAULT 0,
    status_code INT NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_marketing_sync_campaign (campaign_id),
    KEY idx_marketing_sync_tenancy (tenancy_id),
    KEY idx_marketing_sync_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
