CREATE TABLE IF NOT EXISTS campaign_voice_schedules (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED NOT NULL,
    tenancy_id CHAR(36) NOT NULL,
    name VARCHAR(100) NOT NULL,
    type ENUM('torpedo','voice') NOT NULL,
    total_contacts INT UNSIGNED NOT NULL DEFAULT 0,
    job_id VARCHAR(64) NOT NULL,
    queue_id VARCHAR(64) NULL,
    status ENUM('pending','processing','done','cancelled','failed') NOT NULL DEFAULT 'pending',
    total_calls INT UNSIGNED NOT NULL DEFAULT 0,
    answered_calls INT UNSIGNED NOT NULL DEFAULT 0,
    failed_calls INT UNSIGNED NOT NULL DEFAULT 0,
    scheduled_at DATETIME NOT NULL,
    campaign_id INT UNSIGNED NULL,
    payload_json LONGTEXT NULL,
    note TEXT NULL,
    processed_at DATETIME NULL,
    error_message TEXT NULL,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_campaign_voice_schedules_job_id (job_id),
    KEY idx_campaign_voice_schedules_due (status, scheduled_at),
    KEY idx_campaign_voice_schedules_user (user_id),
    KEY idx_campaign_voice_schedules_tenancy (tenancy_id),
    KEY idx_campaign_voice_schedules_campaign (campaign_id)
);
