CREATE TABLE IF NOT EXISTS public_demo_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    channel VARCHAR(20) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(190) NULL,
    ip_address VARCHAR(64) NOT NULL,
    user_agent VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'received',
    message VARCHAR(255) NULL,
    turnstile_success TINYINT(1) NOT NULL DEFAULT 0,
    turnstile_error VARCHAR(255) NULL,
    provider_response JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_public_demo_ip_channel_created (ip_address, channel, created_at),
    KEY idx_public_demo_phone_channel_created (phone, channel, created_at),
    KEY idx_public_demo_email_channel_created (email, channel, created_at),
    KEY idx_public_demo_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
