CREATE TABLE IF NOT EXISTS site_service_tests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(190) NOT NULL,
    service_type ENUM('voice','sms','whatsapp') NOT NULL,
    destination VARCHAR(30) NULL,
    status VARCHAR(30) DEFAULT 'pending',
    provider VARCHAR(80) NULL,
    provider_message_id VARCHAR(120) NULL,
    provider_response JSON NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(255) NULL,
    request_payload JSON NULL,
    error_message TEXT NULL,
    sent_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_email_service (email, service_type),
    KEY idx_service_type (service_type),
    KEY idx_status (status),
    KEY idx_created_at (created_at),
    KEY idx_ip_address (ip_address)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
