CREATE TABLE IF NOT EXISTS campaign_dispatch_schedules (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenancy_id VARCHAR(64) NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    channel VARCHAR(24) NOT NULL,
    native_table VARCHAR(80) NULL,
    native_id BIGINT NULL,
    legacy_schedule_id BIGINT NULL,
    schedule_name VARCHAR(180) NOT NULL,
    dedupe_key VARCHAR(191) NOT NULL,
    timezone VARCHAR(80) NOT NULL DEFAULT 'America/Sao_Paulo',
    scheduled_at DATETIME NOT NULL,
    available_at DATETIME NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'scheduled',
    dispatch_mode VARCHAR(32) NOT NULL DEFAULT 'native',
    payload_json LONGTEXT NULL,
    run_after_failure_at DATETIME NULL,
    last_error TEXT NULL,
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts INT UNSIGNED NOT NULL DEFAULT 5,
    locked_at DATETIME NULL,
    locked_by VARCHAR(120) NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_campaign_dispatch_dedupe (dedupe_key),
    KEY idx_campaign_dispatch_due (status, available_at),
    KEY idx_campaign_dispatch_channel_status (channel, status),
    KEY idx_campaign_dispatch_native (native_table, native_id),
    KEY idx_campaign_dispatch_tenancy (tenancy_id, user_id),
    KEY idx_campaign_dispatch_locked (locked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS campaign_dispatch_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    schedule_id BIGINT UNSIGNED NOT NULL,
    worker_type VARCHAR(40) NOT NULL,
    worker_name VARCHAR(160) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'running',
    queued_count INT UNSIGNED NOT NULL DEFAULT 0,
    processed_count INT UNSIGNED NOT NULL DEFAULT 0,
    failed_count INT UNSIGNED NOT NULL DEFAULT 0,
    context_json LONGTEXT NULL,
    error_message TEXT NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_campaign_dispatch_runs_schedule (schedule_id, started_at),
    KEY idx_campaign_dispatch_runs_status (status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS campaign_dispatch_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    schedule_id BIGINT UNSIGNED NULL,
    run_id BIGINT UNSIGNED NULL,
    tenancy_id VARCHAR(64) NOT NULL,
    user_id INT UNSIGNED NULL,
    channel VARCHAR(24) NOT NULL,
    level VARCHAR(20) NOT NULL DEFAULT 'info',
    event_name VARCHAR(80) NOT NULL,
    message VARCHAR(255) NOT NULL,
    context_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_campaign_dispatch_logs_schedule (schedule_id, created_at),
    KEY idx_campaign_dispatch_logs_run (run_id, created_at),
    KEY idx_campaign_dispatch_logs_channel (channel, created_at),
    KEY idx_campaign_dispatch_logs_tenancy (tenancy_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS campaign_sms_queue (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    schedule_id BIGINT UNSIGNED NOT NULL,
    native_campaign_id BIGINT NULL,
    batch_id BIGINT NULL,
    tenancy_id VARCHAR(64) NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    contact_phone VARCHAR(32) NOT NULL,
    contact_name VARCHAR(190) NULL,
    service_type VARCHAR(16) NOT NULL DEFAULT 'short',
    charset_msg VARCHAR(8) NOT NULL DEFAULT '0',
    message_body TEXT NOT NULL,
    sms_units INT UNSIGNED NOT NULL DEFAULT 1,
    partner_id VARCHAR(100) NOT NULL,
    dedupe_key VARCHAR(191) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    available_at DATETIME NOT NULL,
    locked_at DATETIME NULL,
    locked_by VARCHAR(120) NULL,
    sent_at DATETIME NULL,
    callback_id BIGINT NULL,
    attempts INT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts INT UNSIGNED NOT NULL DEFAULT 5,
    last_error TEXT NULL,
    provider_response_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_campaign_sms_queue_dedupe (dedupe_key),
    KEY idx_campaign_sms_queue_due (status, available_at),
    KEY idx_campaign_sms_queue_schedule (schedule_id, status),
    KEY idx_campaign_sms_queue_batch (batch_id),
    KEY idx_campaign_sms_queue_tenancy (tenancy_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
